### PR TITLE
Functional app of core features

### PR DESCRIPTION
**Pull request by quicodesfor**
Create a named tour. 
Add and remove tour stops.
See tour stop/landmark details.
Delete tour.

### CODE REVIEW

**Comment by JohnLeeroy** [comment]
Looks like a lot of good progress!  
I like the fact we are using Travis CI.

Do we want to compile the code using Android N?

**Comment by JohnLeeroy** [comment]
125 files changed so it'll take me a while but I'll check it out commit by commit.  I would recommend breaking up all the changes into smaller bite-size pull-requests in the future.

**Comment by quicodesfor** [comment]
Normally I would but there was nothing yet so for the initial core functionality, I just wrote all of it.
Realistically, if it runs and functions like you want, merge.
Create issues from there and iterate from there.

**Comment by quicodesfor** [comment]
As for building against N, it's just the target. The min version is 16 and I've tested against 18 with no crashes so it should be fine for now.
Versions can be changed as necessary.

**Comment by fatdzo** [comment]
First of all let me say thank you for the work.

As far as core functionality goes, there was something built in it, at least I think. It fetched the data from the db and had some models and structure to it, had some basic views. There is even an entire readme dedicated how to work with the project. I was getting ready to fill in create issues related to the new design.

If you had any problems with the existing implementation I would gladly discussed it with you and made changes and even helped you out if you thought something was wrong.

Second of all, I am the lead of the Walking Tours Android project and was not aware that you were working on it until this morning, like I said earlier, if you had a problem with my code base or my leadership I would gladly discussed it with you.

I will look at the code, I want to decipher it, hopefully merge it and we will continue on from there.

**Comment by JohnLeeroy** [comment]
I haven't updated my environment to support Android N yet so I haven't built the code but I did take a look at the commits.  It looked like you bulldozed over the existing code and implemented a lot more features.  

The new code looks well written but overwriting the existing implementation without communicating with the other project members is iffy.  I would communicate with @fatdzo and see how you two can collaborate on figuring the next steps for the PR.

**Comment by ToxicBakery** [comment]
I believe rewriting a lot of the features was necessary in this case as it has significant changes to the dependencies which required changes to all existing code. Reading through everything, this looks very well written and the changes to the gradle versions and deps using ext combined with the arrays is awesome. Im actually going to start doing that as currently I have been using a version.properties in a similar fashion but its not as clean as this.

@quicodesfor this all looks great in my opinion

**Comment by ToxicBakery** [comment]
@quicodesfor you don't have any contact information. Would you mind emailing me or hitting me up on any of the slacks? 

slack: `ian.shaun.thomas`
email: toxicbakery@gmail.com

**Pull request merged**
